### ISSUE TITLE
NameError: uninitialized constant #<Class:#<Chef::Recipe:0x0000000009664a00>>::Chocolatey

### ISSUE THREAD

**Issue by mgiammarco** [chocolatey/chocolatey-cookbook#142]
### Cookbook version
2.0.1

### Chef-client version
15.1.36

### Platform Details
Windows 10

### Scenario:
Trying to install chocolatey with chef-run or chef-apply

### Steps to Reproduce:
Launched chef-run or chef-apply on default.rb

### Expected Result:
Install chocolatey on target system

### Actual Result:
On remote failed to converge and no log.
On local I see the log that says:

> Generated at 2019-07-29 20:59:36 +0200
NameError: uninitialized constant #<Class:#<Chef::Recipe:0x0000000007eee678>>::Chocolatey
..\Downloads\chocolatey\recipes\default.rb:25:in `run_chef_recipe'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/apply.rb:195:in `instance_eval'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/apply.rb:195:in `run_chef_recipe'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/apply.rb:209:in `run_application'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/apply.rb:222:in `run'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.1.36/bin/chef-apply:24:in `<top (required)>'
C:/opscode/chef-workstation/modules/chef/../../bin/chef-apply:359:in `load'
C:/opscode/chef-workstation/modules/chef/../../bin/chef-apply:359:in `<main>'

**Comment by mgiammarco** [comment]
Nobody can help me? It seems strange to me to get a NameError: uninitialized constant #<Class:#Chef::Recipe:0x0000000007eee678>::Chocolatey on a freshly installed Chef Workstation

**Comment by ferventcoder** [comment]
Paging @tas50 - not sure if you see notifications.
